var markers = [
 {
   "BuildingID": "812478",
   "LandlordID": "812478",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "35",
   "LowHouseNumber": "35",
   "HighHouseNumber": "35",
   "StreetName": "HOLLAND AVENUE",
   "StreetCode": "33200",
   "Zip": "10303",
   "Full Address": "35 HOLLAND AVENUE 10303",
   "Apartment": "",
   "Story": "0",
   "num": "287",
   "a": "48",
   "b": "209",
   "c": "30",
   "i": "0",
   "dob": "7",
   "BIN": "5109140",
   "dob_hpd": "294",
   "score": "2.06154",
   "A_UNITS": "130",
   "B_UNITS": "0",
   "OWNER1": "NORTH SHORE PLAZA PRESERVATION DP, L.P",
   "ORGANIZATION": "NORTH SHORE PLAZA PRESERVATION DP, L.P",
   "OWNER1_LN": "RADDICK",
   "OWNER1_FN": "BRIAN",
   "officer": "BRIAN RADDICK",
   "org": "NORTH SHORE PLAZA PRESERVATION DP, L.P",
   "exclude": "0",
   "lat": "40.639682",
   "lng": "-74.1711983",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "797473",
   "LandlordID": "746071",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "99",
   "LowHouseNumber": "99",
   "HighHouseNumber": "99",
   "StreetName": "WRIGHT STREET",
   "StreetCode": "56450",
   "Zip": "10304",
   "Full Address": "99 WRIGHT STREET 10304",
   "Apartment": "",
   "Story": "0",
   "num": "203",
   "a": "36",
   "b": "103",
   "c": "61",
   "i": "3",
   "dob": "0",
   "BIN": "5013684",
   "dob_hpd": "203",
   "score": "48.625",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": "GRINBERG MANAGEMENT AND DEVELOPMENT",
   "ORGANIZATION": "GRINBERG MANAGEMENT AND DEVELOPMENT",
   "OWNER1_LN": "GRINBERG",
   "OWNER1_FN": "GARY",
   "officer": "GARY GRINBERG",
   "org": "GRINBERG MANAGEMENT AND DEVELOPMENT",
   "exclude": "0",
   "lat": "40.627892",
   "lng": "-74.0791245",
   "worstLandlord": "1",
   "dof": "1",
   "dof": "1"
 },
 {
   "BuildingID": "790359",
   "LandlordID": "790359",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "411",
   "LowHouseNumber": "411",
   "HighHouseNumber": "411",
   "StreetName": "VANDERBILT AVENUE",
   "StreetCode": "52850",
   "Zip": "10304",
   "Full Address": "411 VANDERBILT AVENUE 10304",
   "Apartment": "25",
   "Story": "0",
   "num": "178",
   "a": "24",
   "b": "130",
   "c": "21",
   "i": "3",
   "dob": "1",
   "BIN": "5016362",
   "dob_hpd": "179",
   "score": "9.61765",
   "A_UNITS": "17",
   "B_UNITS": "0",
   "OWNER1": "DELAWARE ARMS INC",
   "ORGANIZATION": "DELAWARE ARMS INC",
   "OWNER1_LN": "JENNINGS",
   "OWNER1_FN": "RALPH",
   "officer": "RALPH JENNINGS",
   "org": "DELAWARE ARMS INC",
   "exclude": "0",
   "lat": "40.615894",
   "lng": "-74.0841064",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "812544",
   "LandlordID": "290622",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "1300",
   "LowHouseNumber": "1300",
   "HighHouseNumber": "1300",
   "StreetName": "RICHMOND AVENUE",
   "StreetCode": "44750",
   "Zip": "10314",
   "Full Address": "1300 RICHMOND AVENUE 10314",
   "Apartment": "",
   "Story": "0",
   "num": "175",
   "a": "37",
   "b": "131",
   "c": "5",
   "i": "2",
   "dob": "0",
   "BIN": "5128872",
   "dob_hpd": "175",
   "score": "3.4625",
   "A_UNITS": "40",
   "B_UNITS": "0",
   "OWNER1": "BRIDGEVIEW ASSOCIATES",
   "ORGANIZATION": "BRIDGEVIEW ASSOCIATES",
   "OWNER1_LN": "WEISS",
   "OWNER1_FN": "DAVID",
   "officer": "DAVID WEISS",
   "org": "BRIDGEVIEW ASSOCIATES",
   "exclude": "0",
   "lat": "40.616715",
   "lng": "-74.1566641",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "793709",
   "LandlordID": null,
   "Boro": "STATEN ISLAND",
   "HouseNumber": "410",
   "LowHouseNumber": "410",
   "HighHouseNumber": "410",
   "StreetName": "WESTERVELT AVENUE",
   "StreetCode": "54950",
   "Zip": "10301",
   "Full Address": "410 WESTERVELT AVENUE 10301",
   "Apartment": "2",
   "Story": "0",
   "num": "141",
   "a": "14",
   "b": "92",
   "c": "33",
   "i": "2",
   "dob": "0",
   "BIN": "5000752",
   "dob_hpd": "141",
   "score": "47.1667",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "ARDOLIC",
   "OWNER1_FN": "ZUHRA",
   "officer": "ZUHRA ARDOLIC",
   "org": null,
   "exclude": "0",
   "lat": "40.638195",
   "lng": "-74.0820847",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "746071",
   "LandlordID": "746071",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "60",
   "LowHouseNumber": "60",
   "HighHouseNumber": "60",
   "StreetName": "HOLLAND AVENUE",
   "StreetCode": "33200",
   "Zip": "10303",
   "Full Address": "60 HOLLAND AVENUE 10303",
   "Apartment": "",
   "Story": "0",
   "num": "131",
   "a": "16",
   "b": "81",
   "c": "33",
   "i": "1",
   "dob": "0",
   "BIN": "5028645",
   "dob_hpd": "131",
   "score": "32.625",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": "GRINBERG MANAGEMENT & DEVELOPMENT",
   "ORGANIZATION": "GRINBERG MANAGEMENT & DEVELOPMENT",
   "OWNER1_LN": "GRINBERG",
   "OWNER1_FN": "GARY",
   "officer": "GARY GRINBERG",
   "org": "GRINBERG MANAGEMENT & DEVELOPMENT",
   "exclude": "0",
   "lat": "40.638832",
   "lng": "-74.1715546",
   "worstLandlord": "1",
   "dof": "2",
   "dof": "2"
 },
 {
   "BuildingID": "768885",
   "LandlordID": "768885",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "90",
   "LowHouseNumber": "90",
   "HighHouseNumber": "90",
   "StreetName": "PARK AVENUE",
   "StreetCode": "42650",
   "Zip": "10302",
   "Full Address": "90 PARK AVENUE 10302",
   "Apartment": "21",
   "Story": "3",
   "num": "91",
   "a": "20",
   "b": "71",
   "c": "0",
   "i": "0",
   "dob": "1",
   "BIN": "5023728",
   "dob_hpd": "92",
   "score": "4.05556",
   "A_UNITS": "0",
   "B_UNITS": "18",
   "OWNER1": "SPPN REALTY LLC",
   "ORGANIZATION": "SPPN REALTY LLC",
   "OWNER1_LN": "PATEL",
   "OWNER1_FN": "SAVITABEN K",
   "officer": "SAVITABEN K PATEL",
   "org": "SPPN REALTY LLC",
   "exclude": "0",
   "lat": "40.638382",
   "lng": "-74.131897",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "791834",
   "LandlordID": "791834",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "90",
   "LowHouseNumber": "90",
   "HighHouseNumber": "90",
   "StreetName": "VREELAND STREET",
   "StreetCode": "53600",
   "Zip": "10302",
   "Full Address": "90 VREELAND STREET 10302",
   "Apartment": "",
   "Story": "1",
   "num": "80",
   "a": "11",
   "b": "63",
   "c": "5",
   "i": "1",
   "dob": "3",
   "BIN": "5023991",
   "dob_hpd": "83",
   "score": "4.78125",
   "A_UNITS": "3",
   "B_UNITS": "13",
   "OWNER1": "FIRST STREET REALTY, LLC",
   "ORGANIZATION": "FIRST STREET REALTY, LLC",
   "OWNER1_LN": "PARKER",
   "OWNER1_FN": "KENNETH",
   "officer": "KENNETH PARKER",
   "org": "FIRST STREET REALTY, LLC",
   "exclude": "0",
   "lat": "40.637138",
   "lng": "-74.1331329",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "1"
 },
 {
   "BuildingID": "717681",
   "LandlordID": "717681",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "44",
   "LowHouseNumber": "44",
   "HighHouseNumber": "44",
   "StreetName": "BRIGHTON AVENUE",
   "StreetCode": "19850",
   "Zip": "10301",
   "Full Address": "44 BRIGHTON AVENUE 10301",
   "Apartment": "",
   "Story": "0",
   "num": "76",
   "a": "10",
   "b": "57",
   "c": "6",
   "i": "3",
   "dob": "4",
   "BIN": "5002497",
   "dob_hpd": "80",
   "score": "24.6667",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": "JWL ENTERPRISES",
   "ORGANIZATION": "JWL ENTERPRISES",
   "OWNER1_LN": "LAFORTE",
   "OWNER1_FN": "JOSEPH",
   "officer": "JOSEPH LAFORTE",
   "org": "JWL ENTERPRISES",
   "exclude": "0",
   "lat": "40.637115",
   "lng": "-74.0882263",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "794394",
   "LandlordID": "794394",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "51",
   "LowHouseNumber": "51",
   "HighHouseNumber": "51",
   "StreetName": "WILBUR STREET",
   "StreetCode": "55400",
   "Zip": "10309",
   "Full Address": "51 WILBUR STREET 10309",
   "Apartment": "",
   "Story": "0",
   "num": "69",
   "a": "8",
   "b": "53",
   "c": "7",
   "i": "1",
   "dob": "6",
   "BIN": "5082754",
   "dob_hpd": "75",
   "score": "3.28261",
   "A_UNITS": "1",
   "B_UNITS": "22",
   "OWNER1": "GUDDEMI PROPERTIES INC",
   "ORGANIZATION": "GUDDEMI PROPERTIES INC",
   "OWNER1_LN": "GUDDEMI",
   "OWNER1_FN": "ANTHONY",
   "officer": "ANTHONY GUDDEMI",
   "org": "GUDDEMI PROPERTIES INC",
   "exclude": "0",
   "lat": "40.515537",
   "lng": "-74.1946945",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "789648",
   "LandlordID": "717681",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "1042",
   "LowHouseNumber": "1042",
   "HighHouseNumber": "1042",
   "StreetName": "VAN DUZER STREET",
   "StreetCode": "52550",
   "Zip": "10304",
   "Full Address": "1042 VAN DUZER STREET 10304",
   "Apartment": "",
   "Story": "0",
   "num": "69",
   "a": "9",
   "b": "48",
   "c": "8",
   "i": "4",
   "dob": "0",
   "BIN": "5016054",
   "dob_hpd": "69",
   "score": "20",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "LAFORTE",
   "OWNER1_FN": "JOSEPH",
   "officer": "JOSEPH LAFORTE",
   "org": null,
   "exclude": "0",
   "lat": "40.613693",
   "lng": "-74.0876389",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "717977",
   "LandlordID": "717977",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "209",
   "LowHouseNumber": "209",
   "HighHouseNumber": "209",
   "StreetName": "BROAD STREET",
   "StreetCode": "20300",
   "Zip": "10304",
   "Full Address": "209 BROAD STREET 10304",
   "Apartment": "",
   "Story": "0",
   "num": "65",
   "a": "25",
   "b": "35",
   "c": "5",
   "i": "0",
   "dob": "3",
   "BIN": "5014053",
   "dob_hpd": "68",
   "score": "12.125",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": "J&M BROAD PROPERTY LLC",
   "ORGANIZATION": "J&M BROAD PROPERTY LLC",
   "OWNER1_LN": "ALI",
   "OWNER1_FN": "JAMAL M",
   "officer": "JAMAL M ALI",
   "org": "J&M BROAD PROPERTY LLC",
   "exclude": "0",
   "lat": "40.624146",
   "lng": "-74.0818405",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "789070",
   "LandlordID": "789070",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "61",
   "LowHouseNumber": "61",
   "HighHouseNumber": "61",
   "StreetName": "TYSEN STREET",
   "StreetCode": "52100",
   "Zip": "10301",
   "Full Address": "61 TYSEN STREET 10301",
   "Apartment": "",
   "Story": "0",
   "num": "66",
   "a": "13",
   "b": "38",
   "c": "15",
   "i": "0",
   "dob": "0",
   "BIN": "5001741",
   "dob_hpd": "66",
   "score": "20.1667",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": "UKRAPPROP 2 LLC",
   "ORGANIZATION": "UKRAPPROP 2 LLC",
   "OWNER1_LN": "GARANIN",
   "OWNER1_FN": "VSEVOLOD",
   "officer": "VSEVOLOD GARANIN",
   "org": "UKRAPPROP 2 LLC",
   "exclude": "0",
   "lat": "40.644108",
   "lng": "-74.0993042",
   "worstLandlord": "0",
   "dof": "1",
   "dof": "1"
 },
 {
   "BuildingID": "749665",
   "LandlordID": null,
   "Boro": "STATEN ISLAND",
   "HouseNumber": "264",
   "LowHouseNumber": "264",
   "HighHouseNumber": "264",
   "StreetName": "JEWETT AVENUE",
   "StreetCode": "34850",
   "Zip": "10302",
   "Full Address": "264 JEWETT AVENUE 10302",
   "Apartment": "1F",
   "Story": "1",
   "num": "65",
   "a": "21",
   "b": "36",
   "c": "6",
   "i": "2",
   "dob": "0",
   "BIN": "5024355",
   "dob_hpd": "65",
   "score": "11.25",
   "A_UNITS": "4",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "YOUBOTY",
   "OWNER1_FN": "EVA",
   "officer": "EVA YOUBOTY",
   "org": null,
   "exclude": "0",
   "lat": "40.630596",
   "lng": "-74.1306763",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "717679",
   "LandlordID": null,
   "Boro": "STATEN ISLAND",
   "HouseNumber": "42",
   "LowHouseNumber": "42",
   "HighHouseNumber": "42",
   "StreetName": "BRIGHTON AVENUE",
   "StreetCode": "19850",
   "Zip": "10301",
   "Full Address": "42 BRIGHTON AVENUE 10301",
   "Apartment": "3FL",
   "Story": "3",
   "num": "59",
   "a": "20",
   "b": "26",
   "c": "10",
   "i": "3",
   "dob": "5",
   "BIN": "5002498",
   "dob_hpd": "64",
   "score": "17",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": null,
   "ORGANIZATION": null,
   "OWNER1_LN": "DOLAN",
   "OWNER1_FN": "JOHN",
   "officer": "JOHN DOLAN",
   "org": null,
   "exclude": "0",
   "lat": "40.637173",
   "lng": "-74.0881958",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "790373",
   "LandlordID": "790373",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "487",
   "LowHouseNumber": "487",
   "HighHouseNumber": "489",
   "StreetName": "VANDERBILT AVENUE",
   "StreetCode": "52850",
   "Zip": "10304",
   "Full Address": "487 VANDERBILT AVENUE 10304",
   "Apartment": "",
   "Story": "0",
   "num": "60",
   "a": "13",
   "b": "31",
   "c": "16",
   "i": "0",
   "dob": "0",
   "BIN": "5016476",
   "dob_hpd": "60",
   "score": "18.3333",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": "487 VANDERBILT AVE LLC",
   "ORGANIZATION": "487 VANDERBILT AVE LLC",
   "OWNER1_LN": "VELLIOS",
   "OWNER1_FN": "MARIA",
   "officer": "MARIA VELLIOS",
   "org": "487 VANDERBILT AVE LLC",
   "exclude": "0",
   "lat": "40.614586",
   "lng": "-74.0858383",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "793683",
   "LandlordID": "793683",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "344",
   "LowHouseNumber": "344",
   "HighHouseNumber": "344",
   "StreetName": "WESTERVELT AVENUE",
   "StreetCode": "54950",
   "Zip": "10301",
   "Full Address": "344 WESTERVELT AVENUE 10301",
   "Apartment": "",
   "Story": "0",
   "num": "42",
   "a": "1",
   "b": "34",
   "c": "6",
   "i": "1",
   "dob": "18",
   "BIN": "5000820",
   "dob_hpd": "60",
   "score": "13.1667",
   "A_UNITS": "6",
   "B_UNITS": "0",
   "OWNER1": "WESTERVELT PROPERTY LLC",
   "ORGANIZATION": "WESTERVELT PROPERTY LLC",
   "OWNER1_LN": "HARWOOD",
   "OWNER1_FN": "MICHAEL",
   "officer": "MICHAEL HARWOOD",
   "org": "WESTERVELT PROPERTY LLC",
   "exclude": "0",
   "lat": "40.639679",
   "lng": "-74.0822525",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "1"
 },
 {
   "BuildingID": "782970",
   "LandlordID": "768885",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "1",
   "LowHouseNumber": "1",
   "HighHouseNumber": "3",
   "StreetName": "SLOSSON TERRACE",
   "StreetCode": "48200",
   "Zip": "10301",
   "Full Address": "1 SLOSSON TERRACE 10301",
   "Apartment": "",
   "Story": "0",
   "num": "57",
   "a": "9",
   "b": "46",
   "c": "1",
   "i": "1",
   "dob": "1",
   "BIN": "5000039",
   "dob_hpd": "58",
   "score": "3.3",
   "A_UNITS": "1",
   "B_UNITS": "14",
   "OWNER1": "1-3 SLOSSON TERRACE, INC",
   "ORGANIZATION": "1-3 SLOSSON TERRACE, INC",
   "OWNER1_LN": "PATEL",
   "OWNER1_FN": "SAVITABEN K",
   "officer": "SAVITABEN K PATEL",
   "org": "1-3 SLOSSON TERRACE, INC",
   "exclude": "0",
   "lat": "40.639828",
   "lng": "-74.0757523",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 },
 {
   "BuildingID": "718042",
   "LandlordID": "718042",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "91",
   "LowHouseNumber": "91",
   "HighHouseNumber": "91",
   "StreetName": "BROAD STREET",
   "StreetCode": "20300",
   "Zip": "10304",
   "Full Address": "91 BROAD STREET 10304",
   "Apartment": "",
   "Story": "1",
   "num": "57",
   "a": "18",
   "b": "26",
   "c": "12",
   "i": "1",
   "dob": "0",
   "BIN": "5013778",
   "dob_hpd": "57",
   "score": "7.33333",
   "A_UNITS": "6",
   "B_UNITS": "0",
   "OWNER1": "91 BROAD STREET REALTY LLC",
   "ORGANIZATION": "91 BROAD STREET REALTY LLC",
   "OWNER1_LN": "BARRETTI",
   "OWNER1_FN": "PHILIP",
   "officer": "PHILIP BARRETTI",
   "org": "91 BROAD STREET REALTY LLC",
   "exclude": "0",
   "lat": "40.625213",
   "lng": "-74.078491",
   "worstLandlord": "0",
   "dof": "2",
   "dof": "0"
 },
 {
   "BuildingID": "744871",
   "LandlordID": "744871",
   "Boro": "STATEN ISLAND",
   "HouseNumber": "136",
   "LowHouseNumber": "136",
   "HighHouseNumber": "136",
   "StreetName": "HENDRICKS AVENUE",
   "StreetCode": "32750",
   "Zip": "10301",
   "Full Address": "136 HENDRICKS AVENUE 10301",
   "Apartment": "",
   "Story": "0",
   "num": "56",
   "a": "22",
   "b": "30",
   "c": "4",
   "i": "0",
   "dob": "0",
   "BIN": "5000997",
   "dob_hpd": "56",
   "score": "12",
   "A_UNITS": "3",
   "B_UNITS": "0",
   "OWNER1": "JB SI HOLDINGS 1 LLC",
   "ORGANIZATION": "JB SI HOLDINGS 1 LLC",
   "OWNER1_LN": "BIONDOLILLO",
   "OWNER1_FN": "JOSEPH",
   "officer": "JOSEPH BIONDOLILLO",
   "org": "JB SI HOLDINGS 1 LLC",
   "exclude": "0",
   "lat": "40.639843",
   "lng": "-74.0859985",
   "worstLandlord": "0",
   "dof": "0",
   "dof": "0"
 }
];
	
	var lng = "";
	var count = "";
	var pins = "";
		
		
	
var hotel = "";
var Rank = "";
var buildings = "";
var aunits = "";
var bunits = "";
var units = "";
var hpd = "";
var dob = "";
var hc = "";
var name = "";
var map = "";
var cajahotelHTML = "";
var hotelContainerHTML = "";
	var lng = "";
	var count = "";
	var pins = "";
		
		
	
var hotel = "";
var Rank = "";
var buildings = "";
var aunits = "";
var bunits = "";
var units = "";
var hpd = "";
var dob = "";
var hc = "";
var name = "";
var map = "";
var cajahotelHTML = "";
var cajahotelHTML2 = "";
var cajahotelHTML3 = "";
var addstring = "";
var hotelContainerHTML = "";
var org = "";
		var replaced = "";




 				

    for (var j = 0; j < markers.length; j++){
	var data=markers[j];
if (markers[j].DOF > 0)
		{
			var DOF2 = "Yes";
		}
		else{
			DOF2= "No";
		}
		var box = "";
		replaced = markers[j].StreetName.split(' ').join('+');
		var lat = "";
		address = '<headll>' + markers[j].HouseNumber + ' ' + markers[j].StreetName + ', ' + markers[j].Boro + ' ' + markers[j].Zip + '</headll>';
		org = '<div class="pnum">Organization: ' + markers[j].org + '</div>';
		Rank = '<div class="pnum">Landlord Rank <g>' + markers[j].Rank + '</g></div>';
		var	Rank2 = '<headll>' + markers[j].Rank + '. </headll>';
		addstring = '' + markers[j].HouseNumber + '+' + replaced + ',+' + markers[j].Boro + ',+' + markers[j].Zip + ''
		buildings = '<pnum>Number of Buildings ' + markers[j].buildings + '</pnum>';
		hpd = '<div class="pnum">Number of HPD Violations <d>' + markers[j].num + '</d></div>';
		dob = '<div class="pnum">Number of DOB Violations <d>' + markers[j].dob + '</d></div>';
		hc = '<div class="pnum">Number of Housing Court Actions <d>' + markers[j].housingCourt + '</d></div>';
		name = '' + markers[j].officer + '';
				var name2 = '<div class="pnum">Landlord: ' + markers[j].officer + '</div>';
	dof = '<div class="pnum">Tax lien sold in last two years : <d>' + DOF2 + '</d></div>';
		map = '<div id="' + markers[j].DIVH + '" style="top: 10px; left: 25px; width:100%; height:85%; float: left"></div>';
		lat = '' + markers[j].lat + ',' + markers[j].lng + '';
			
	
	
		var url = 'https://maps.googleapis.com/maps/api/streetview?size=600x400&location=' + addstring + '%20&fov=90&pitch=0%20&key=AIzaSyCEdL7GSizXOkrhG1vJWSRro4wlyqo5kdU';
		 box += '<div class="col-md-13"><div class="col-md-12-head"><headll>' + address + '</headll></div><div class="col-md-2"> <a href="map.html"><img class="img-responsive" alt="landlordmap" src="img/si/si' + (j+1) + '.jpeg"></a></div><div class="col-md-3"><div class="buildingRates"></span><span>' + name2 + '</span><span>' + org + '</span><span>' + units + '</span><span>' + hpd + '</span><span>' + dob + '</span><span>' + dof + '</span></div></div></div>';
			
		
	
	
	cajahotelHTML =   box  ;
	

  hotelContainerHTML += cajahotelHTML;
}

var outputDiv = document.getElementById('scrollDiv');
outputDiv.innerHTML = hotelContainerHTML;







